/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ElectricalRouteImport } from './routes/electrical'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlarmsPowerQualityRouteImport } from './routes/alarms.power-quality'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as IndexRouteImport } from './routes/index'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricalRoute = ElectricalRouteImport.update({
  id: '/electrical',
  path: '/electrical',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsPowerQualityRoute = AlarmsPowerQualityRouteImport.update({
  id: '/alarms/power-quality',
  path: '/alarms/power-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/alarms/power-quality': typeof AlarmsPowerQualityRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/data-health': typeof DataHealthRoute
  '/demand': typeof DemandRoute
  '/electrical': typeof ElectricalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/alarms/power-quality': typeof AlarmsPowerQualityRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/data-health': typeof DataHealthRoute
  '/demand': typeof DemandRoute
  '/electrical': typeof ElectricalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/alarms/power-quality': typeof AlarmsPowerQualityRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/data-health': typeof DataHealthRoute
  '/demand': typeof DemandRoute
  '/electrical': typeof ElectricalRoute
  '/opportunities': typeof OpportunitiesRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/alarms/power-quality'
    | '/analytics'
    | '/billing'
    | '/data-health'
    | '/demand'
    | '/electrical'
    | '/opportunities'
    | '/portfolio'
    | '/reports'
    | '/savings'
    | '/sustainability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/alarms/power-quality'
    | '/analytics'
    | '/billing'
    | '/data-health'
    | '/demand'
    | '/electrical'
    | '/opportunities'
    | '/portfolio'
    | '/reports'
    | '/savings'
    | '/sustainability'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/alarms/power-quality'
    | '/analytics'
    | '/billing'
    | '/data-health'
    | '/demand'
    | '/electrical'
    | '/opportunities'
    | '/portfolio'
    | '/reports'
    | '/savings'
    | '/sustainability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  AlarmsPowerQualityRoute: typeof AlarmsPowerQualityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  DataHealthRoute: typeof DataHealthRoute
  DemandRoute: typeof DemandRoute
  ElectricalRoute: typeof ElectricalRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  SavingsRoute: typeof SavingsRoute
  SustainabilityRoute: typeof SustainabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrical': {
      id: '/electrical'
      path: '/electrical'
      fullPath: '/electrical'
      preLoaderRoute: typeof ElectricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms/power-quality': {
      id: '/alarms/power-quality'
      path: '/alarms/power-quality'
      fullPath: '/alarms/power-quality'
      preLoaderRoute: typeof AlarmsPowerQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  AlarmsPowerQualityRoute: AlarmsPowerQualityRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  DataHealthRoute: DataHealthRoute,
  DemandRoute: DemandRoute,
  ElectricalRoute: ElectricalRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  SavingsRoute: SavingsRoute,
  SustainabilityRoute: SustainabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
